const EN = {
    title: "Stock Management Web Application: OPTIM'STOCK",
    introduction:
        "OPTIM'STOCK is a web application designed to meet the needs of modern businesses. Developed by Youness JELLOULI, it provides a comprehensive and intuitive solution for optimizing stock management, orders, and customers.",
    introductionHeading: 'Introduction',
    introductionText:
        "OPTIM'STOCK is a web application designed to meet the needs of modern businesses. Developed by Youness JELLOULI, it provides a comprehensive and intuitive solution for optimizing stock management, orders, and customers.",
    productManagementTitle: 'Product Management',
    productManagement1: 'Add, modify, and delete products',
    productManagement2: 'Classification by categories and subcategories',
    productManagement3: 'Real-time stock tracking',
    productManagement4: 'Setting stock alert levels',
    productManagement5: 'Import and export of product data',
    ordersTitle: 'Order Management',
    orders1: 'Creation and tracking of customer orders',
    orders2: 'Management of available stocks and reservations',
    orders3: 'Application of discounts and promotions',
    orders4: 'Generation of invoices and delivery notes',
    orders5: 'Integration with online payment platforms',
    customersTitle: 'Customer Management',
    customers1: 'Creation and tracking of customer profiles',
    customers2: 'Segmentation and marketing targeting',
    customers3: 'History of orders and payments',
    customers4: 'Analysis of buying behavior',
    suppliersTitle: 'Supplier Management',
    suppliers1: 'Creation and tracking of supplier profiles',
    suppliers2: 'Negotiation of prices and purchase conditions',
    suppliers3: 'Tracking of orders and deliveries',
    suppliers4: 'Management of disputes and claims',
    otherFeaturesTitle: 'Other Features',
    otherFeatures1: 'Dashboard with key performance indicators (KPI)',
    otherFeatures2: 'Reports and analyses customizables',
    otherFeatures3: 'User and permission management',
    otherFeatures4: 'Data backup and restoration',
    benefitsTitle: 'Benefits',
    benefits1Title: 'Improvement of inventory management ',
    benefits2Title: 'Saving time and efficiency ',
    benefits3Title: 'Better decision making ',
    benefits4Title: 'Increased customer satisfaction ',
    benefits1: "Improved stock management: OPTIM'STOCK allows real-time tracking of available stocks and minimizes stockouts.",
    benefits2: 'Time and efficiency gains: Automation of repetitive tasks allows focus on higher-value activities.',
    benefits3: 'Better decision-making: Customizable reports provide a clear view of the activity and support strategic decisions.',
    benefits4: 'Increased customer satisfaction: Effective management of orders and deliveries improves customer satisfaction.',
    technologiesUsedTitle: 'Technologies Used',
    technologiesUsedFrontend: ' HTML, CSS, Bootstrap, JavaScript',
    technologiesUsedBackend: ' PHP',
    technologiesUsedDatabase: ' MySQL',
    technologiesUsedDevelopmentTools: ' Git, Xampp, MySQL WorkBench',
    overviewTitle: 'Overview',
    conclusionTitle: 'Conclusion',
    conclusionText:
        "OPTIM'STOCK is a powerful and flexible web-based stock management application that adapts to the needs of all types of businesses. Leveraging modern technologies and intuitive design, it enhances stock management, increases productivity, and boosts customer satisfaction."
};

export default EN;
