const FR = {
    title: "Application Web de Gestion de Stock : OPTIM'STOCK",
    introduction:
        "OPTIM'STOCK est une application web de gestion de stock conçue pour répondre aux besoins des entreprises modernes. Développée par Youness JELLOULI, elle offre une solution complète et intuitive pour optimiser la gestion des stocks, des commandes et des clients.",
    introductionHeading: 'Introduction',
    introductionText:
        "OPTIM'STOCK est une application web de gestion de stock conçue pour répondre aux besoins des entreprises modernes. Développée par Youness JELLOULI, elle offre une solution complète et intuitive pour optimiser la gestion des stocks, des commandes et des clients.",
    productManagementTitle: 'Gestion des Produits',
    productManagement1: 'Ajout, modification et suppression de produits',
    productManagement2: 'Classification par catégories et sous-catégories',
    productManagement3: 'Suivi des stocks en temps réel',
    productManagement4: "Définition des niveaux d'alerte de stock",
    productManagement5: 'Importation et exportation de données produits',
    ordersTitle: 'Gestion des Commandes',
    orders1: 'Création et suivi des commandes clients',
    orders2: 'Gestion des stocks disponibles et des réservations',
    orders3: 'Application de remises et promotions',
    orders4: 'Génération de factures et de bons de livraison',
    orders5: 'Intégration avec les plateformes de paiement en ligne',
    customersTitle: 'Gestion des Clients',
    customers1: 'Création et suivi des fiches clients',
    customers2: 'Segmentation et ciblage marketing',
    customers3: 'Historique des commandes et des paiements',
    customers4: "Analyse du comportement d'achat",
    suppliersTitle: 'Gestion des Fournisseurs',
    suppliers1: 'Création et suivi des fiches fournisseurs',
    suppliers2: "Négociation des prix et des conditions d'achat",
    suppliers3: 'Suivi des commandes et des livraisons',
    suppliers4: 'Gestion des litiges et des réclamations',
    otherFeaturesTitle: 'Autres Fonctionnalités',
    otherFeatures1: 'Tableau de bord avec des indicateurs clés de performance (KPI)',
    otherFeatures2: 'Rapports et analyses personnalisables',
    otherFeatures3: 'Gestion des utilisateurs et des permissions',
    otherFeatures4: 'Sauvegarde et restauration des données',
    benefitsTitle: 'Avantages',
    benefits1Title: 'Amélioration de la gestion des stocks ',
    benefits2Title: "Gain de temps et d'efficacité ",
    benefits3Title: 'Meilleure prise de décision ',
    benefits4Title: 'Satisfaction client accrue ',
    benefits1: ": OPTIM'STOCK permet de suivre en temps réel les stocks disponibles et de minimiser les ruptures de stock.",
    benefits2: ": L'automatisation des tâches répétitives permet de se concentrer sur des activités à plus forte valeur ajoutée.",
    benefits3:
        ": Les rapports et analyses personnalisables offrent une vision claire de l'activité et permettent de prendre des décisions stratégiques.",
    benefits4: ": La gestion efficace des commandes et des livraisons permet d'améliorer la satisfaction client.",
    technologiesUsedTitle: 'Technologies Utilisées',
    technologiesUsedFrontend: 'HTML, CSS, Bootstrap, JavaScript',
    technologiesUsedBackend: 'PHP',
    technologiesUsedDatabase: ' MySQL',
    technologiesUsedDevelopmentTools: ' Git, Xampp, MySQL WorkBench',
    overviewTitle: 'Overview',
    conclusionTitle: 'Conclusion',
    conclusionText:
        "OPTIM'STOCK est une application web de gestion de stock puissante et flexible qui s'adapte aux besoins de tous types d'entreprises. En s'appuyant sur des technologies modernes et une conception intuitive, elle permet d'améliorer la gestion des stocks, d'accroître la productivité et de booster la satisfaction client."
};

export default FR;
